# Generated by Django 3.0.8 on 2020-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200924_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_avatar',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
